import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'locale_provider.dart';

class AppLocalizations {
  static const Map<String, String> _ar = {
    // Core
    'World Cup 2026': 'كأس العالم 2026',
    'WORLD CUP 2026': 'كأس العالم 2026',
    'Predict. Compete. Win.': 'توقع. نافس. فز.',
    'Select language': 'اختر اللغة',
    'Language': 'اللغة',
    'English': 'الإنجليزية',
    'العربية': 'العربية',
    'Language saved': 'تم حفظ اللغة بنجاح',
    'Dark mode': 'الوضع الداكن',
    'Dark theme on': 'تفعيل الوضع الداكن',
    'Light theme on': 'تفعيل الوضع الفاتح',
    'Help & Support': 'الدعم والمساعدة',
    'Profile': 'الملف الشخصي',
    'Edit Profile': 'تعديل الملف الشخصي',
    'Username': 'اسم المستخدم',
    'Save': 'حفظ',
    'Cancel': 'إلغاء',
    'Total Points': 'إجمالي النقاط',
    'Rank': 'الترتيب',
    'Exact Scores': 'النتائج الدقيقة',
    'Correct Results': 'التوقعات الصحيحة',
    'Leagues Joined': 'الدوريات المشتركة',
    'Predictions': 'التوقعات',
    'Joined Leagues': 'الدوريات المنضم إليها',
    'Create Room': 'إنشاء دوري خاص',
    'Join Room': 'الانضمام لدوري خاص',
    'Leaderboard': 'جدول الترتيب',
    'Upcoming Matches': 'المباريات القادمة',
    'Matches': 'المباريات',
    'Points': 'النقاط',
    'Log Out': 'تسجيل الخروج',
    'Log In': 'تسجيل الدخول',
    'Register': 'إنشاء حساب',
    'Password': 'كلمة المرور',
    'Email': 'البريد الإلكتروني',
    'Forgot Password?': 'نسيت كلمة المرور؟',
    'Verify Email': 'تأكيد البريد الإلكتروني',
    'verification code': 'رمز التأكيد',
    'Settings': 'الإعدادات',
    'Admin Panel': 'لوحة التحكم',
    'Leagues': 'الدوريات',
    'Announcements': 'الإعلانات',
    'Rules & Scoring': 'القوانين ونظام النقاط',
    'Predict': 'توقع',
    'Prediction Saved': 'تم حفظ التوقع بنجاح',
    'Lock time': 'وقت الإغلاق',
    'Kickoff': 'البداية',
    'FT': 'نهاية المباراة',
    'Home': 'صاحب الأرض',
    'Away': 'الضيف',
    'Score': 'النتيجة',
    'Result': 'النتيجة',
    'Language Settings': 'إعدادات اللغة',
    'Logout': 'تسجيل الخروج',
    'Are you sure you want to log out?': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'Update FCM Token': 'تحديث رمز الإشعارات',
    'Change Avatar': 'تغيير الصورة الشخصية',
    'Save Profile': 'حفظ التغييرات',
    'Username is too short': 'اسم المستخدم قصير جداً',
    'Successfully updated profile': 'تم تحديث الملف الشخصي بنجاح',
    'FCM token updated': 'تم تحديث رمز الإشعارات بنجاح',
    'General': 'عام',
    'Appearance': 'المظهر',
    'Delete Account': 'حذف الحساب',
    'Are you sure you want to delete your account? This action is permanent and cannot be undone.': 'هل أنت متأكد من رغبتك في حذف حسابك؟ هذا الإجراء نهائي ولا يمكن التراجع عنه.',
    'Room Name': 'اسم الدوري',
    'Max Members': 'الحد الأقصى للأعضاء',
    'Host': 'المنظم',
    'Join Code': 'رمز الانضمام',
    'Copy Code': 'نسخ الرمز',
    'Code Copied!': 'تم نسخ الرمز!',
    'Share Code': 'مشاركة الرمز',
    'Members': 'الأعضاء',
    'No members yet': 'لا يوجد أعضاء بعد',
    'Points earned': 'النقاط المكتسبة',
    'Room Creator': 'منشئ الدوري',
    'No joined leagues yet. Join one or create your own!': 'لم تنضم إلى أي دوري بعد. انضم لدوري أو أنشئ دوريك الخاص!',
    'Search Rooms...': 'البحث عن دوريات...',
    'Enter Room Code': 'أدخل رمز الدوري',
    'Join Private League': 'انضم لدوري خاص',
    'Verification code sent!': 'تم إرسال رمز التأكيد!',
    'Google Sign In': 'الدخول عبر جوجل',
    'Sign In': 'تسجيل الدخول',
    "Don't have an account? Register": 'ليس لديك حساب؟ سجل الآن',
    "Already have an account? Login": 'لديك حساب بالفعل؟ سجل دخولك',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms of Service': 'شروط الخدمة',
    'Email copied to clipboard': 'تم نسخ البريد الإلكتروني',
    'Hide name on global leaderboard': 'إخفاء الاسم في لوحة الترتيب العام',
    'Hide name': 'إخفاء الاسم',
    'Admin panel': 'لوحة التحكم',
    'Manage matches & results': 'إدارة المباريات والنتائج',
    'Account': 'الحساب',
    'Log out': 'تسجيل الخروج',
    'Delete account': 'حذف الحساب',
    'This removes your Firestore profile document and Firebase user when possible, then signs you out. This cannot be undone.': 'سيؤدي هذا إلى حذف حسابك نهائياً من قاعدة البيانات وتسجيل خروجك. لا يمكن التراجع عن هذا الإجراء.',
    'Delete': 'حذف',
    'Live updates from Firestore': 'تحديثات مباشرة من قاعدة البيانات',

    // New Translations
    'Mini Leagues': 'الدوريات المصغرة',

    // Profile Page Additions
    'Stats': 'الإحصائيات',
    'Predictions Made': 'التوقعات المنجزة',
    'Correct Winners': 'الفائزون الصحيحون',
    'Mini leagues': 'الدوريات المصغرة',
    'leagues joined': 'دوريات منضم إليها',
    'Account settings': 'إعدادات الحساب',
    'Notifications': 'الإشعارات',
    'Match reminders & updates': 'تذكيرات وتحديثات المباريات',
    'Accuracy': 'الدقة',
    'Edit profile': 'تعديل الملف الشخصي',

    // Predictions Dashboard Additions
    'Prediction summary': 'ملخص التوقعات',
    'Total predictions': 'إجمالي التوقعات',
    'Correct winners': 'الفائزون الصحيحون',
    'Weekly points': 'النقاط الأسبوعية',
    'Global Rank': 'الترتيب العالمي',
    'Weekly Joker status': 'حالة الجوكر الأسبوعية',
    'Joker available this week': 'الجوكر متاح هذا الأسبوع',
    'Joker used this week': 'الجوكر المستخدم هذا الأسبوع',
    'Joker used this week:\n': 'الجوكر المستخدم هذا الأسبوع:\n',
    'Competition': 'البطولة',
    'All Leagues': 'جميع الدوريات',
    'Filter by League': 'تصفية حسب الدوري',
    'Filter by Date': 'تصفية حسب التاريخ',
    'Finished': 'المنتهية',
    'Live': 'مباشر',
    'Upcoming': 'القادمة',
    'No upcoming predictions.': 'لا توجد توقعات قادمة.',
    'No live predictions.': 'لا توجد توقعات مباشرة.',
    'No finished predictions yet.': 'لا توجد توقعات منتهية بعد.',
    'Winner': 'الفائز',
    'Draw': 'تعادل',
    'Joker': 'الجوكر',
    'Final Score': 'النتيجة النهائية',
    'Current Score': 'النتيجة الحالية',
    'Final': 'النهائي',
    'Edit locked': 'تم قفل التعديل',
    'Edit prediction': 'تعديل التوقع',

    // Mini Leagues Additions
    'Join league': 'الانضمام لدوري',
    'Invite code': 'رمز الدعوة',
    'Join': 'انضم',
    'My Leagues': 'دورياتي',
    'Join League': 'انضمام لدوري',
    'Create': 'إنشاء',
    'No leagues yet. Create one!': 'لا توجد دوريات بعد. أنشئ واحداً!',
    'members': 'أعضاء',
    'Join a league with an invite code': 'انضم إلى دوري باستخدام رمز الدعوة',
    'Enter invite code': 'أدخل رمز الدعوة',

    // Leaderboard Additions
    'Failed to load': 'فشل التحميل',
    'Retry': 'إعادة المحاولة',
    'No rankings yet': 'لا توجد ترتيبات بعد',
    'pts': 'نقطة',
    'YOU': 'أنت',

    // Leagues Names
    'Premier League': 'الدوري الإنجليزي الممتاز',
    'La Liga': 'الدوري الإسباني',
    'Serie A': 'الدوري الإيطالي',
    'Bundesliga': 'الدوري الألماني',
    'Ligue 1': 'الدوري الفرنسي',
    'Champions League': 'دوري أبطال أوروبا',
    'Europa League': 'الدوري الأوروبي',
    'AFCON': 'كأس الأمم الأفريقية',
    'Copa America': 'كوبا أمريكا',
    'World Cup': 'كأس العالم',
    'Saudi Pro League': 'الدوري السعودي للمحترفين',
    'Qatar Stars League': 'دوري نجوم قطر',
    'Jordanian Pro League': 'الدوري الأردني للمحترفين',
    'Botola Pro': 'البطولة الوطنية المغربية',
    'Iraqi League': 'الدوري العراقي',

    // Matches Screen & Fixtures Additions
    'All upcoming': 'كل المباريات القادمة',
    'Today': 'اليوم',
    'Tomorrow': 'غداً',
    'Latest': 'الحدث',
    'Results Today': 'نتائج اليوم',
    'Yesterday': 'أمس',
    'Before Yesterday': 'أول أمس',
    'No upcoming fixtures.': 'لا توجد مباريات قادمة.',
    'No fixtures for this filter.': 'لا توجد مباريات لهذا الفلتر.',
    '(Live)': '(مباشر)',
    '(FT)': '(نهاية المباراة)',
    'Waiting for result...': 'في انتظار النتيجة...',
    'Match alert canceled': 'تم إلغاء تنبيه المباراة',
    'Match alert set': 'تم تعيين تنبيه المباراة',
    'Alerted': 'مُنبَّه',
    'Alert': 'تنبيه',
    'Predictions are closed for this match': 'التوقعات مغلقة لهذه المباراة',
    'Pick a Competition': 'اختر بطولة',
    'Coming soon': 'قريباً',
    'Loading...': 'جاري التحميل...',
    'upcoming': 'قادمة',
    'predictions': 'توقع',
    'UPCOMING': 'القادمة',
    'LIVE': 'مباشر',
    'FINISHED': 'المنتهية',
    'Prediction': 'التوقع',
    'Close': 'إغلاق',
    'Standings': 'الترتيب',
  };

  static String translate(String key, String localeCode) {
    if (localeCode == 'ar') {
      return _ar[key] ?? key;
    }
    return key;
  }
}

extension TranslationExtension on String {
  String tr(WidgetRef ref) {
    final locale = ref.watch(localeProvider);
    return AppLocalizations.translate(this, locale);
  }
}
